### ISSUE TITLE
Dawn and other times

### ISSUE THREAD

**Issue by brettz9** [janrg/MeeusSunMoon#3]
Hi Jan,

Another library I was using had the following additional items:

- nadir
- sunriseEnd
- sunsetStart
- dawn
- dusk
- nauticalDawn
- nauticalDusk
- nightEnd
- night
- goldenHourEnd
- goldenHour

Would it be difficult to add these, in particular dawn?

**Comment by janrg** [comment]
I'll need to take a look but I imagine some of them will be fairly easy to add. I'll see when I have time but should be able to do this at the very latest in December.
What I should definitely be able to add is civil, nautical, and astronomical dawn and dusk. (I imagine dawn and dusk in your list refer to astronomical dawn and dusk?).
I'm not sure what nightEnd and night refer to in your list.
goldenHour is a bit of a fuzzy concept and I don't think there'd be a particular benefit to add something like that in, as the times for sunrise and sunset should be sufficient to get an idea of when that is.
For anything other than the 3 dawns and dusks I'd need an additional source of reliable and accurate data that I can test against. For nadir I could potentially just take it as exactly the midpoint between sunset and sunrise which should be reasonably accurate.

**Comment by janrg** [comment]
I see, the page does explain how he uses the terms.
dawn/dusk -> civil dawn/dusk
nauticalDawn/nauticalDusk is clear
night/nightEnd -> astronomical dusk/dawn
For sunriseEnd and sunsetStarts (the *lower* edge of the sun touching the horizon) I don't think there would be much usefulness derived from addding them. Golden hour (which he essentially takes as the opposite of civil dawn/dusk, i.e. the sun being 6° *above* the horizon, I've already mentioned.
So I'd narrow down this CR to adding the three dawns and dusks + potentially nadir, though for nadir I'll have to think a bit more about how to implement this (suncalc just uses 6 hours before dawn, which I'm not sure I'm happy with, but then its calculations are significantly less precise anyway) and if I can find a reliable reference for nadir times somewhere.

**Comment by janrg** [comment]
Implemented in https://github.com/janrg/MeeusSunMoon/releases/tag/v2.1.0

**Comment by brettz9** [comment]
This looks great, thanks a lot!
