### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PitWiener** [janrg/MeeusSunMoon#9]
Hi!
Thanks for MeeusSunMoon but I get an error:
1st I declare
```
    <script type='text/javascript' src='moment-with-locales.min.js' charset='utf-8'></script>
    <script type='text/javascript' src='moment-timezone-with-data.min.js' charset='utf-8'></script>
    <script src="dist/meeussunmoon.min.js"></script>
```
but when I start my test app I get the error:
`   TypeError: r.tz is not a function | meeussunmoon.min.js:7:11538
`
What's wrong?
Thanks
Pit

**Comment by janrg** [comment]
Hi, could you share a code-snippet of how you're using the library? Also could you try with the non-minified version in order to get a useful line number in the error output?

**Comment by PitWiener** [comment]
Thanks for your fast response.
I solved the problem: I had a wrong date conversion.   :-{
Thanks Pit

**Comment by janrg** [comment]
Glad you got it solved :-)
